/******************************************************************************

 @file tiop_config.h

 @brief TI OpenThread stack configuration parameters

 DO NOT EDIT - This file is generated by the SysConfig tool.

 *****************************************************************************/

#ifndef TIOP_CONFIG_H_
#define TIOP_CONFIG_H_

#include <openthread/instance.h>
#include <openthread/joiner.h>

/**
 * MLE Link Mode R
 */
#ifndef TIOP_CONFIG_LINK_MODE_R
#define TIOP_CONFIG_LINK_MODE_R    1
#endif

/**
 * MLE Link Mode D
 */
#ifndef TIOP_CONFIG_LINK_MODE_D
#define TIOP_CONFIG_LINK_MODE_D    1
#endif

/**
 * Data poll period for Sleepy End Devices
 */
#ifndef TIOP_CONFIG_POLL_PERIOD
#define TIOP_CONFIG_POLL_PERIOD    2000
#endif

/**
 * Default IEEE 802.15.4 channel
 */
#ifndef TIOP_CONFIG_LINK_CHANNEL
#define TIOP_CONFIG_LINK_CHANNEL   14
#endif

/**
 * Default radio TX power in dBm
 */
#ifndef TIOP_CONFIG_TX_POWER
#define TIOP_CONFIG_TX_POWER       0
#endif

/**
 * Pre-Shared Key (PSKd) for joiner devices
 */
#ifndef TIOP_CONFIG_PSKD
#define TIOP_CONFIG_PSKD           "PSK001"
#endif

/**
 * Setting the Extended Address is done in the Device Configuration Module
 */

/*
 * If 1, set the Extended Address, PAN ID, Extended PAN ID, and Network Key using
 * the parameters defined by TIOP_CONFIG_EXT_ADDR, TIOP_CONFIG_PAN_ID,
 * TIOP_CONFIG_EXT_PAN_ID, and TIOP_CONFIG_NETWORK_KEY_U/L.
 * If 0, do not set these parameters, leaving them as default. This should be used
 * when setting these parameters via the commissioning process.
 */
#ifndef TIOP_CONFIG_SET_NW_ID
#define TIOP_CONFIG_SET_NW_ID      1
#endif

/*
 * IEEE 802.15.4 PAN ID
 */
#ifndef TIOP_CONFIG_PAN_ID
#define TIOP_CONFIG_PAN_ID         0xFFFF
#endif

/*
 * Thread Extended PAN ID
 */
#ifndef TIOP_CONFIG_EXT_PAN_ID
#define TIOP_CONFIG_EXT_PAN_ID     0xdead00beef00cafe
#endif

/*
 * Thread Network Key (split into upper and lower 8 bytes)
 */
#ifndef TIOP_CONFIG_NETWORK_KEY_U
#define TIOP_CONFIG_NETWORK_KEY_U   0x0011223344556677
#endif
#ifndef TIOP_CONFIG_NETWORK_KEY_L
#define TIOP_CONFIG_NETWORK_KEY_L   0x8899AABBCCDDEEFF
#endif

/*
 * Network Name
 */
#define TIOP_CONFIG_NETWORK_NAME   "OpenThread"

/*
 * @brief Wrapper function around otJoinerStart for joining the network with the
 *        Pre-Shared Key (PSKd) defined in TIOP_CONFIG_PSKD
 *
 * @param  aInstance         A pointer to an OpenThread instance.
 * @param  aProvisioningUrl  A pointer to the Provisioning URL (may be NULL).
 * @param  aVendorName       A pointer to the Vendor Name (must be static).
 * @param  aVendorModel      A pointer to the Vendor Model (must be static).
 * @param  aVendorSwVersion  A pointer to the Vendor SW Version (must be static).
 * @param  aVendorData       A pointer to the Vendor Data (must be static).
 * @param  aCallback         A pointer to a function that is called when the join operation completes.
 * @param  aContext          A pointer to application-specific context.
 *
 * @retval OT_ERROR_NONE              Successfully started the Commissioner role.
 * @retval OT_ERROR_INVALID_ARGS      @p aPSKd or @p aProvisioningUrl is invalid.
 * @retval OT_ERROR_DISABLED_FEATURE  The Joiner feature is not enabled in this build.
 */
extern otError TIOP_configuredJoinerStart(otInstance *     aInstance,
                                          const char *     aProvisioningUrl,
                                          const char *     aVendorName,
                                          const char *     aVendorModel,
                                          const char *     aVendorSwVersion,
                                          const char *     aVendorData,
                                          otJoinerCallback aCallback,
                                          void *           aContext);

/*
 * @brief Configuration function which applies stack configurations via OpenThread API
 *
 * @param aInstance  A pointer to the OpenThread instance to configure.
 */
extern void TIOP_init(otInstance * aInstance);

#endif /* TIOP_CONFIG_H_ */

