################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
src/core/meshcop/announce_begin_client.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/announce_begin_client.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/border_agent.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/border_agent.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/commissioner.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/commissioner.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/dataset.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/dataset.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/dataset_local.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/dataset_local.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/dataset_manager.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/dataset_manager.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/dataset_manager_ftd.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/dataset_manager_ftd.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/dataset_updater.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/dataset_updater.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/dtls.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/dtls.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/energy_scan_client.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/energy_scan_client.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/extended_panid.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/extended_panid.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/joiner.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/joiner.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/joiner_router.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/joiner_router.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/meshcop.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/meshcop.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/meshcop_leader.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/meshcop_leader.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/meshcop_tlvs.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/meshcop_tlvs.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/network_name.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/network_name.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/panid_query_client.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/panid_query_client.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/meshcop/timestamp.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/meshcop/timestamp.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/meshcop/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


