################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
src/core/net/checksum.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/checksum.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/dhcp6_client.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/dhcp6_client.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/dhcp6_server.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/dhcp6_server.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/dns_client.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/dns_client.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/dns_dso.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/dns_dso.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/dns_types.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/dns_types.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/dnssd_server.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/dnssd_server.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/icmp6.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/icmp6.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/ip4_address.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/ip4_address.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/ip6.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/ip6.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/ip6_address.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/ip6_address.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/ip6_filter.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/ip6_filter.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/ip6_headers.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/ip6_headers.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/ip6_mpl.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/ip6_mpl.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/nd_agent.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/nd_agent.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/netif.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/netif.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/sntp_client.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/sntp_client.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/socket.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/socket.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/srp_client.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/srp_client.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/srp_server.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/srp_server.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/tcp6.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/tcp6.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/net/udp6.o: C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core/net/udp6.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1030/ccs/tools/compiler/ti-cgt-armllvm_1.3.0.LTS/bin/tiarmclang.exe" -c -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian -mthumb -Oz -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/examples/platforms" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/third_party/mbedtls/repo/include" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/include" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libmbedcrypto_cc13x2_26x2_ticlang/config" -I"C:/Users/Workstation/Desktop/IPR/BR/cc2652_code/libopenthread_ftd_cc13x2_26x2_ticlang/config" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src/core" -I"C:/ti/simplelink_cc13xx_cc26xx_sdk_6_20_00_29/source/third_party/openthread/src" -DHAVE_CONFIG_H -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -DMBEDTLS_CONFIG_FILE='"mbedtls-config-cc13x2_26x2.h"' -DDeviceFamily_CC13X2_CC26X2 -DOPENTHREAD_FTD=1 -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc13x2_26x2-config.h"' -DOPENTHREAD_CONFIG_FILE='"openthread-config-cc13x2_26x2-ftd.h"' -gstrict-dwarf -gdwarf-3 -Wextra -Wshadow -Wall -Wno-ti-macros -ffunction-sections -march=armv7e-m -MMD -MP -MF"src/core/net/$(basename $(<F)).d_raw" -MT"$(@)"  $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


